In [1]:
import numpy as np
import matplotlib.pyplot as plt
import time
from sklearn import datasets

dataset = datasets.load_iris()

In [2]:
print("Keys of the dataset: {}".format(dataset.keys()))

Keys of the dataset: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [3]:
print("Target names: {}".format(dataset.target_names))

Target names: ['setosa' 'versicolor' 'virginica']


In [4]:
print("Feature names: {}".format(dataset.feature_names))

Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [5]:
print("Shape of data: {}".format(dataset.data.shape))

Shape of data: (150, 4)


In [6]:
print("First five samples:\n {}".format(dataset.data[:5]))

First five samples:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [7]:
print("Shape of target: {}".format(dataset.target.shape))

Shape of target: (150,)


In [8]:
print("Target:\n {}".format(dataset.target))

Target:
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(dataset.data, dataset.target, test_size=0.3, random_state=0)

print("X_train shape: {}".format(X_train.shape))
print("y_train shape: {}".format(y_train.shape))
print("X_test shape: {}".format(X_test.shape))
print("y_test shape: {}".format(y_test.shape))

X_train shape: (105, 4)
y_train shape: (105,)
X_test shape: (45, 4)
y_test shape: (45,)


In [10]:
from sklearn.neighbors import NearestCentroid
mdc = NearestCentroid()
mdc.fit(X_train, y_train)
y_pred = mdc.predict(X_test)
print("Test set predictions:\n {}".format(y_pred))
print("Test set score:\n {:.3f}".format(mdc.score(X_test, y_test)))
print("Test set score:\n {:.3f}".format(np.mean(y_pred==y_test)))

Execution time: 0.0009982585906982422 seconds
Test set predictions:
 [2 1 0 2 0 2 0 1 2 1 2 1 1 1 1 0 1 1 0 0 1 1 0 0 1 0 0 1 1 0 2 1 0 1 2 1 0
 1 1 1 2 0 2 0 0]
Test set score:
 0.911
Test set score:
 0.911


In [11]:
from mdc import mdc_classifier

y_pred = mdc_classifier(X_train, y_train, X_test)
print("Test set predictions:\n {}".format(y_pred))
print("Test set score:\n {:.3f}".format(np.mean(y_pred == y_test)))



Execution time: 0.0009982585906982422 seconds
Test set predictions:
 [2, 1, 0, 2, 0, 2, 0, 1, 2, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 2, 1, 0, 1, 2, 1, 0, 1, 1, 1, 2, 0, 2, 0, 0]
Test set score:
 0.911
